---
title: "Analysis of single-cell RNA of covid-19 data"
author: "ZHAO Kai"
fontsize: 10pt
output: pdf_document
---

```{r, size="small"}
suppressPackageStartupMessages({
    require(ggplot2)
    require(gridExtra)
    require(reshape2)
    require(hrbrthemes)
    require(extrafont)
})
options(scipen=10)
```


```{r fig.height=5, fig.width = 10}
setwd("~/Documents/Research/SC2/result_for_response")

runtime <- read.csv("runtime.csv", header = T)

p1 <- ggplot(subset(runtime, sample_size < 30000), aes(x=sample_size, y=minutes)) +
  geom_line(size = 1, color = "deepskyblue") + xlab("Sample Size") + ylab("Minutes") +
  theme_ipsum(base_family = "Times", base_size= 11, axis_title_size = 11) + theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) + scale_x_continuous(breaks = seq(min(1000), max(30000), by = 4000))

p2 <- ggplot(subset(runtime, sample_size > 30000), aes(x=as.numeric(sample_size), y=minutes)) +
  geom_line(size = 1, color = "deepskyblue") + xlab("Sample Size") + ylab("Minutes") +
  theme_ipsum(base_family = "Times", base_size= 11, axis_title_size = 11) + theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) + scale_x_continuous(breaks = seq(min(100000), max(500000), by = 50000))

grid.arrange(p1, p2, ncol=2)
```

```{r fig.height=5, fig.width = 10}
setwd("~/Documents/Research/SC2/result_for_response")

runtime <- read.csv("gene_number_runtime.csv", header = T)

p1 <- ggplot(runtime[1:5,], aes(x=gene_number, y=minutes)) +
  geom_line(size = 1, color = "deepskyblue") + xlab("Gene number") + ylab("Minutes") +
  theme_ipsum(base_family = "Times", base_size= 11, axis_title_size = 11) + theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) 

p2 <- ggplot(runtime[6:10,], aes(x=gene_number, y=minutes)) +
  geom_line(size = 1, color = "deepskyblue") + xlab("Gene number") + ylab("Minutes") +
  theme_ipsum(base_family = "Times", base_size= 11, axis_title_size = 11) + theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) 
grid.arrange(p1, p2, ncol=2)
```